// Every place Scripture tells us not to be afraid, in canonical order.
// Text: Berean Standard Bible (BSB), public domain. Generated from the BSB text; do not hand-edit wording.
window.VERSES = [
  { ref: "Genesis 15:1", text: "After these events, the word of the LORD came to Abram in a vision: “Do not be afraid, Abram. I am your shield, your very great reward.”" },
  { ref: "Genesis 21:17", text: "Then God heard the voice of the boy, and the angel of God called to Hagar from heaven, “What is wrong, Hagar? Do not be afraid, for God has heard the voice of the boy where he lies." },
  { ref: "Genesis 26:24", text: "and that night the LORD appeared to him and said, “I am the God of your father Abraham. Do not be afraid, for I am with you. I will bless you and multiply your descendants for the sake of My servant Abraham.”" },
  { ref: "Genesis 35:17", text: "During her severe labor, the midwife said to her, “Do not be afraid, for you are having another son.”" },
  { ref: "Genesis 43:23", text: "“It is fine,” said the steward. “Do not be afraid. Your God, the God of your father, gave you the treasure that was in your sacks. I received your silver.” Then he brought Simeon out to them." },
  { ref: "Genesis 46:3", text: "“I am God,” He said, “the God of your father. Do not be afraid to go down to Egypt, for I will make you into a great nation there." },
  { ref: "Genesis 50:19", text: "But Joseph replied, “Do not be afraid. Am I in the place of God?" },
  { ref: "Genesis 50:21", text: "Therefore do not be afraid. I will provide for you and your little ones.” So Joseph reassured his brothers and spoke kindly to them." },
  { ref: "Exodus 14:13", text: "But Moses told the people, “Do not be afraid. Stand firm and you will see the LORD’s salvation, which He will accomplish for you today; for the Egyptians you see today, you will never see again." },
  { ref: "Exodus 20:20", text: "“Do not be afraid,” Moses replied. “For God has come to test you, so that the fear of Him may be before you, to keep you from sinning.”" },
  { ref: "Leviticus 26:6", text: "And I will give peace to the land, and you will lie down with nothing to fear. I will rid the land of dangerous animals, and no sword will pass through your land." },
  { ref: "Numbers 14:9", text: "Only do not rebel against the LORD, and do not be afraid of the people of the land, for they will be like bread for us. Their protection has been removed, and the LORD is with us. Do not be afraid of them!”" },
  { ref: "Numbers 21:34", text: "But the LORD said to Moses, “Do not fear him, for I have delivered him into your hand, along with all his people and his land. Do to him as you did to Sihon king of the Amorites, who lived in Heshbon.”" },
  { ref: "Deuteronomy 1:17", text: "Show no partiality in judging; hear both small and great alike. Do not be intimidated by anyone, for judgment belongs to God. And bring to me any case too difficult for you, and I will hear it.”" },
  { ref: "Deuteronomy 1:21", text: "See, the LORD your God has placed the land before you. Go up and take possession of it as the LORD, the God of your fathers, has told you. Do not be afraid or discouraged.”" },
  { ref: "Deuteronomy 1:29", text: "So I said to you: “Do not be terrified or afraid of them!" },
  { ref: "Deuteronomy 3:2", text: "But the LORD said to me, “Do not fear him, for I have delivered him into your hand, along with all his people and his land. Do to him as you did to Sihon king of the Amorites, who lived in Heshbon.”" },
  { ref: "Deuteronomy 3:22", text: "Do not be afraid of them, for the LORD your God Himself will fight for you.”" },
  { ref: "Deuteronomy 7:18", text: "But do not be afraid of them. Be sure to remember what the LORD your God did to Pharaoh and all Egypt:" },
  { ref: "Deuteronomy 7:21", text: "Do not be terrified by them, for the LORD your God, who is among you, is a great and awesome God." },
  { ref: "Deuteronomy 18:22", text: "When a prophet speaks in the name of the LORD and the message does not come to pass or come true, that is a message the LORD has not spoken. The prophet has spoken presumptuously. Do not be afraid of him." },
  { ref: "Deuteronomy 20:1", text: "When you go out to war against your enemies and see horses, chariots, and an army larger than yours, do not be afraid of them; for the LORD your God, who brought you out of the land of Egypt, is with you." },
  { ref: "Deuteronomy 20:3", text: "saying to them, “Hear, O Israel, today you are going into battle with your enemies. Do not be fainthearted or afraid; do not be alarmed or terrified because of them." },
  { ref: "Deuteronomy 31:6", text: "Be strong and courageous; do not be afraid or terrified of them, for it is the LORD your God who goes with you; He will never leave you nor forsake you.”" },
  { ref: "Deuteronomy 31:8", text: "The LORD Himself goes before you; He will be with you. He will never leave you nor forsake you. Do not be afraid or discouraged.”" },
  { ref: "Joshua 1:9", text: "Have I not commanded you to be strong and courageous? Do not be afraid; do not be discouraged, for the LORD your God is with you wherever you go.”" },
  { ref: "Joshua 8:1", text: "Then the LORD said to Joshua, “Do not be afraid or discouraged. Take the whole army with you, and go up and attack Ai. See, I have delivered into your hand the king of Ai, his people, his city, and his land." },
  { ref: "Joshua 10:8", text: "The LORD said to Joshua, “Do not be afraid of them, for I have delivered them into your hand. Not one of them shall stand against you.”" },
  { ref: "Joshua 10:25", text: "“Do not be afraid or discouraged,” Joshua said. “Be strong and courageous, for the LORD will do this to all the enemies you fight.”" },
  { ref: "Joshua 11:6", text: "Then the LORD said to Joshua, “Do not be afraid of them, for by this time tomorrow I will deliver all of them slain before Israel. You are to hamstring their horses and burn up their chariots.”" },
  { ref: "Judges 6:23", text: "But the LORD said to him, “Peace be with you. Do not be afraid, for you will not die.”" },
  { ref: "Ruth 3:11", text: "And now do not be afraid, my daughter. I will do for you whatever you request, since all my fellow townspeople know that you are a woman of noble character." },
  { ref: "1 Samuel 12:20", text: "“Do not be afraid,” Samuel replied. “Even though you have committed all this evil, do not turn aside from following the LORD, but serve the LORD with all your heart." },
  { ref: "1 Samuel 22:23", text: "Stay with me; do not be afraid, for he who seeks your life is seeking mine as well. You will be safe with me.”" },
  { ref: "1 Samuel 23:17", text: "saying, “Do not be afraid, for my father Saul will never lay a hand on you. And you will be king over Israel, and I will be your second-in-command. Even my father Saul knows this is true.”" },
  { ref: "2 Samuel 9:7", text: "“Do not be afraid,” said David, “for surely I will show you kindness for the sake of your father Jonathan. I will restore to you all the land of your grandfather Saul, and you will always eat at my table.”" },
  { ref: "1 Kings 17:13", text: "“Do not be afraid,” Elijah said to her. “Go and do as you have said. But first make me a small cake of bread from what you have, and bring it out to me. Afterward, make some for yourself and your son," },
  { ref: "2 Kings 1:15", text: "Then the angel of the LORD said to Elijah, “Go down with him. Do not be afraid of him.” So Elijah got up and went down with him to the king." },
  { ref: "2 Kings 6:16", text: "“Do not be afraid,” Elisha answered, “for those who are with us are more than those who are with them.”" },
  { ref: "2 Kings 19:6", text: "who replied, “Tell your master that this is what the LORD says: ‘Do not be afraid of the words you have heard, with which the servants of the king of Assyria have blasphemed Me." },
  { ref: "2 Kings 25:24", text: "And Gedaliah took an oath before them and their men, assuring them, “Do not be afraid of the servants of the Chaldeans. Live in the land and serve the king of Babylon, and it will be well with you.”" },
  { ref: "1 Chronicles 22:13", text: "Then you will succeed, if you carefully follow the statutes and ordinances that the LORD commanded Moses for Israel. Be strong and courageous. Do not be afraid or discouraged." },
  { ref: "1 Chronicles 28:20", text: "David also said to Solomon his son, “Be strong and courageous, and do it. Do not be afraid or discouraged, for the LORD God, my God, is with you. He will neither fail you nor forsake you before all the work for the service of the house of the LORD is finished." },
  { ref: "2 Chronicles 20:15", text: "And he said, “Listen, all you people of Judah and Jerusalem! Listen, King Jehoshaphat! This is what the LORD says: ‘Do not be afraid or discouraged because of this vast army, for the battle does not belong to you, but to God." },
  { ref: "2 Chronicles 20:17", text: "You need not fight this battle. Take up your positions, stand firm, and see the salvation of the LORD on your behalf, O Judah and Jerusalem. Do not be afraid or discouraged. Go out and face them tomorrow, for the LORD is with you.’”" },
  { ref: "2 Chronicles 32:7", text: "“Be strong and courageous! Do not be afraid or discouraged before the king of Assyria and the vast army with him, for there is a greater One with us than with him." },
  { ref: "Nehemiah 4:14", text: "After I had made an inspection, I stood up and said to the nobles, the officials, and the rest of the people, “Do not be afraid of them. Remember the Lord, who is great and awesome, and fight for your brothers, your sons and your daughters, your wives and your homes.”" },
  { ref: "Psalm 3:6", text: "I will not fear the myriads set against me on every side." },
  { ref: "Psalm 23:4", text: "Even though I walk through the valley of the shadow of death, I will fear no evil, for You are with me; Your rod and Your staff, they comfort me." },
  { ref: "Psalm 27:1", text: "The LORD is my light and my salvation— whom shall I fear? The LORD is the stronghold of my life— whom shall I dread?" },
  { ref: "Psalm 27:3", text: "Though an army encamps around me, my heart will not fear; though a war breaks out against me, I will keep my trust." },
  { ref: "Psalm 34:4", text: "I sought the LORD, and He answered me; He delivered me from all my fears." },
  { ref: "Psalm 46:2", text: "Therefore we will not fear, though the earth is transformed and the mountains are toppled into the depths of the seas," },
  { ref: "Psalm 49:5", text: "Why should I fear in times of trouble, when wicked usurpers surround me?" },
  { ref: "Psalm 56:3", text: "When I am afraid, I put my trust in You." },
  { ref: "Psalm 56:4", text: "In God, whose word I praise— in God I trust. I will not be afraid. What can man do to me?" },
  { ref: "Psalm 56:11", text: "in God I trust; I will not be afraid. What can man do to me?" },
  { ref: "Psalm 91:5", text: "You will not fear the terror of the night, nor the arrow that flies by day," },
  { ref: "Psalm 112:7", text: "He does not fear bad news; his heart is steadfast, trusting in the LORD." },
  { ref: "Psalm 112:8", text: "His heart is assured; he does not fear, until he looks in triumph on his foes." },
  { ref: "Psalm 118:6", text: "The LORD is on my side; I will not be afraid. What can man do to me?" },
  { ref: "Proverbs 3:24", text: "When you lie down, you will not be afraid; when you rest, your sleep will be sweet." },
  { ref: "Proverbs 3:25", text: "Do not fear sudden danger or the ruin that overtakes the wicked," },
  { ref: "Proverbs 29:25", text: "The fear of man is a snare, but whoever trusts in the LORD is set securely on high." },
  { ref: "Isaiah 7:4", text: "and say to him: Calm down and be quiet. Do not be afraid or disheartened over these two smoldering stubs of firewood—over the fierce anger of Rezin and Aram and of the son of Remaliah." },
  { ref: "Isaiah 8:12", text: "“Do not call conspiracy everything these people regard as conspiracy. Do not fear what they fear; do not live in dread." },
  { ref: "Isaiah 10:24", text: "Therefore this is what the Lord GOD of Hosts says: “O My people who dwell in Zion, do not fear Assyria, who strikes you with a rod and lifts his staff against you as the Egyptians did." },
  { ref: "Isaiah 12:2", text: "Surely God is my salvation; I will trust and not be afraid. For the LORD GOD is my strength and my song, and He also has become my salvation.”" },
  { ref: "Isaiah 35:4", text: "Say to those with anxious hearts: “Be strong, do not fear! Behold, your God will come with vengeance. With divine retribution He will come to save you.”" },
  { ref: "Isaiah 37:6", text: "who replied, “Tell your master that this is what the LORD says: ‘Do not be afraid of the words you have heard, with which the servants of the king of Assyria have blasphemed Me." },
  { ref: "Isaiah 40:9", text: "Go up on a high mountain, O Zion, herald of good news. Raise your voice loudly, O Jerusalem, herald of good news. Lift it up, do not be afraid! Say to the cities of Judah, “Here is your God!”" },
  { ref: "Isaiah 41:10", text: "Do not fear, for I am with you; do not be afraid, for I am your God. I will strengthen you; I will surely help you; I will uphold you with My right hand of righteousness." },
  { ref: "Isaiah 41:13", text: "For I am the LORD your God, who takes hold of your right hand and tells you: Do not fear, I will help you." },
  { ref: "Isaiah 41:14", text: "Do not fear, O worm of Jacob, O few men of Israel. I will help you,” declares the LORD. “Your Redeemer is the Holy One of Israel." },
  { ref: "Isaiah 43:1", text: "Now this is what the LORD says— He who created you, O Jacob, and He who formed you, O Israel: “Do not fear, for I have redeemed you; I have called you by your name; you are Mine!" },
  { ref: "Isaiah 43:5", text: "Do not be afraid, for I am with you; I will bring your offspring from the east and gather you from the west." },
  { ref: "Isaiah 44:2", text: "This is the word of the LORD, your Maker, who formed you from the womb and who will help you: “Do not be afraid, O Jacob My servant, Jeshurun, whom I have chosen." },
  { ref: "Isaiah 44:8", text: "Do not tremble or fear. Have I not told you and declared it long ago? You are My witnesses! Is there any God but Me? There is no other Rock; I know not one.”" },
  { ref: "Isaiah 51:7", text: "Listen to Me, you who know what is right, you people with My law in your hearts: Do not fear the scorn of men; do not be broken by their insults." },
  { ref: "Isaiah 51:12", text: "“I, even I, am He who comforts you. Why should you be afraid of mortal man, of a son of man who withers like grass?" },
  { ref: "Isaiah 54:4", text: "Do not be afraid, for you will not be put to shame; do not be intimidated, for you will not be humiliated. For you will forget the shame of your youth and will remember no more the reproach of your widowhood." },
  { ref: "Isaiah 54:14", text: "In righteousness you will be established, far from oppression, for you will have no fear. Terror will be far removed, for it will not come near you." },
  { ref: "Jeremiah 1:8", text: "Do not be afraid of them, for I am with you to deliver you,” declares the LORD." },
  { ref: "Jeremiah 1:17", text: "Get yourself ready. Stand up and tell them everything that I command you. Do not be intimidated by them, or I will terrify you before them." },
  { ref: "Jeremiah 10:2", text: "This is what the LORD says: “Do not learn the ways of the nations or be terrified by the signs in the heavens, though the nations themselves are terrified by them." },
  { ref: "Jeremiah 10:5", text: "Like scarecrows in a cucumber patch, their idols cannot speak. They must be carried because they cannot walk. Do not fear them, for they can do no harm, and neither can they do any good.”" },
  { ref: "Jeremiah 17:8", text: "He is like a tree planted by the waters that sends out its roots toward the stream. It does not fear when the heat comes, and its leaves are always green. It does not worry in a year of drought, nor does it cease to produce fruit." },
  { ref: "Jeremiah 23:4", text: "I will raise up shepherds over them who will tend them, and they will no longer be afraid or dismayed, nor will any go missing, declares the LORD." },
  { ref: "Jeremiah 30:10", text: "As for you, O Jacob My servant, do not be afraid, declares the LORD, and do not be dismayed, O Israel. For I will surely save you out of a distant place, your descendants from the land of their captivity! Jacob will return to quiet and ease, with no one to make him afraid." },
  { ref: "Jeremiah 40:9", text: "Gedaliah son of Ahikam, the son of Shaphan, swore an oath to them and their men, assuring them, “Do not be afraid to serve the Chaldeans. Live in the land and serve the king of Babylon, and it will go well with you." },
  { ref: "Jeremiah 42:11", text: "Do not be afraid of the king of Babylon, whom you now fear; do not be afraid of him, declares the LORD, for I am with you to save you and deliver you from him." },
  { ref: "Jeremiah 46:27", text: "But you, O Jacob My servant, do not be afraid, and do not be dismayed, O Israel. For I will surely save you out of a distant place, your descendants from the land of their captivity! Jacob will return to quiet and ease, with no one to make him afraid." },
  { ref: "Jeremiah 46:28", text: "And you, My servant Jacob, do not be afraid, declares the LORD, for I am with you. Though I will completely destroy all the nations to which I have banished you, I will not completely destroy you. Yet I will discipline you justly, and will by no means leave you unpunished.”" },
  { ref: "Jeremiah 51:46", text: "Do not let your heart grow faint, and do not be afraid when the rumor is heard in the land; for a rumor will come one year— and then another the next year— of violence in the land and of ruler against ruler." },
  { ref: "Lamentations 3:57", text: "You drew near when I called on You; You said, “Do not be afraid.”" },
  { ref: "Ezekiel 2:6", text: "But you, son of man, do not be afraid of them or their words. Do not be afraid, though briers and thorns surround you, and you dwell among scorpions. Do not be afraid of their words or dismayed by their presence, though they are a rebellious house." },
  { ref: "Ezekiel 3:9", text: "I will make your forehead like a diamond, harder than flint. Do not be afraid of them or dismayed at their presence, even though they are a rebellious house.”" },
  { ref: "Daniel 10:12", text: "“Do not be afraid, Daniel,” he said, “for from the first day that you purposed to understand and to humble yourself before your God, your words were heard, and I have come in response to them." },
  { ref: "Daniel 10:19", text: "“Do not be afraid, you who are highly precious,” he said. “Peace be with you! Be strong now; be very strong!” As he spoke with me, I was strengthened and said, “Speak, my lord, for you have strengthened me.”" },
  { ref: "Joel 2:21", text: "Do not be afraid, O land; rejoice and be glad, for the LORD has done great things." },
  { ref: "Joel 2:22", text: "Do not be afraid, O beasts of the field, for the open pastures have turned green, the trees bear their fruit, and the fig tree and vine yield their best." },
  { ref: "Zephaniah 3:16", text: "On that day they will say to Jerusalem: “Do not fear, O Zion; do not let your hands fall limp." },
  { ref: "Haggai 2:5", text: "This is the promise I made to you when you came out of Egypt. And My Spirit remains among you; do not be afraid.”" },
  { ref: "Zechariah 8:13", text: "As you have been a curse among the nations, O house of Judah and house of Israel, so I will save you, and you will be a blessing. Do not be afraid; let your hands be strong.”" },
  { ref: "Zechariah 8:15", text: "“so now I have resolved to do good again to Jerusalem and Judah. Do not be afraid." },
  { ref: "Matthew 1:20", text: "But after he had pondered these things, an angel of the Lord appeared to him in a dream and said, “Joseph, son of David, do not be afraid to embrace Mary as your wife, for the One conceived in her is from the Holy Spirit." },
  { ref: "Matthew 6:25", text: "Therefore I tell you, do not worry about your life, what you will eat or drink; or about your body, what you will wear. Is not life more than food, and the body more than clothes?" },
  { ref: "Matthew 6:31", text: "Therefore do not worry, saying, ‘What shall we eat?’ or ‘What shall we drink?’ or ‘What shall we wear?’" },
  { ref: "Matthew 6:34", text: "Therefore do not worry about tomorrow, for tomorrow will worry about itself. Today has enough trouble of its own." },
  { ref: "Matthew 8:26", text: "“You of little faith,” Jesus replied, “why are you so afraid?” Then He got up and rebuked the winds and the sea, and it was perfectly calm." },
  { ref: "Matthew 10:19", text: "But when they hand you over, do not worry about how to respond or what to say. In that hour you will be given what to say." },
  { ref: "Matthew 10:26", text: "So do not be afraid of them. For there is nothing concealed that will not be disclosed, and nothing hidden that will not be made known." },
  { ref: "Matthew 10:28", text: "Do not be afraid of those who kill the body but cannot kill the soul. Instead, fear the One who can destroy both soul and body in hell." },
  { ref: "Matthew 10:31", text: "So do not be afraid; you are worth more than many sparrows." },
  { ref: "Matthew 14:27", text: "But Jesus spoke up at once: “Take courage! It is I. Do not be afraid.”" },
  { ref: "Matthew 17:7", text: "Then Jesus came over and touched them. “Get up,” He said. “Do not be afraid.”" },
  { ref: "Matthew 24:6", text: "You will hear of wars and rumors of wars, but see to it that you are not alarmed. These things must happen, but the end is still to come." },
  { ref: "Matthew 28:5", text: "But the angel said to the women, “Do not be afraid, for I know that you are looking for Jesus, who was crucified." },
  { ref: "Matthew 28:10", text: "“Do not be afraid,” said Jesus. “Go and tell My brothers to go to Galilee. There they will see Me.”" },
  { ref: "Mark 4:40", text: "“Why are you so afraid?” He asked. “Do you still have no faith?”" },
  { ref: "Mark 5:36", text: "But Jesus overheard their conversation and said to Jairus, “Do not be afraid; just believe.”" },
  { ref: "Mark 6:50", text: "for they all saw Him and were terrified. But Jesus spoke up at once: “Take courage! It is I. Do not be afraid.”" },
  { ref: "Mark 13:7", text: "When you hear of wars and rumors of wars, do not be alarmed. These things must happen, but the end is still to come." },
  { ref: "Mark 16:6", text: "But he said to them, “Do not be alarmed. You are looking for Jesus the Nazarene, who was crucified. He has risen! He is not here! See the place where they put Him." },
  { ref: "Luke 1:13", text: "But the angel said to him, “Do not be afraid, Zechariah, because your prayer has been heard. Your wife Elizabeth will bear you a son, and you are to give him the name John." },
  { ref: "Luke 1:30", text: "So the angel told her, “Do not be afraid, Mary, for you have found favor with God." },
  { ref: "Luke 2:10", text: "But the angel said to them, “Do not be afraid! For behold, I bring you good news of great joy that will be for all the people:" },
  { ref: "Luke 5:10", text: "and so were his partners James and John, the sons of Zebedee. “Do not be afraid,” Jesus said to Simon. “From now on you will catch men.”" },
  { ref: "Luke 8:50", text: "But Jesus overheard them and said to Jairus, “Do not be afraid; just believe, and she will be healed.”" },
  { ref: "Luke 12:4", text: "I tell you, My friends, do not be afraid of those who kill the body and after that can do no more." },
  { ref: "Luke 12:7", text: "And even the very hairs of your head are all numbered. So do not be afraid; you are worth more than many sparrows." },
  { ref: "Luke 12:11", text: "When you are brought before synagogues, rulers, and authorities, do not worry about how to defend yourselves or what to say." },
  { ref: "Luke 12:22", text: "Then Jesus said to His disciples, “Therefore I tell you, do not worry about your life, what you will eat, or about your body, what you will wear." },
  { ref: "Luke 12:29", text: "And do not be concerned about what you will eat or drink. Do not worry about it." },
  { ref: "Luke 12:32", text: "Do not be afraid, little flock, for your Father is pleased to give you the kingdom." },
  { ref: "Luke 21:9", text: "When you hear of wars and rebellions, do not be alarmed. These things must happen first, but the end is not imminent.”" },
  { ref: "John 6:20", text: "But Jesus spoke up: “It is I; do not be afraid.”" },
  { ref: "John 12:15", text: "“Do not be afraid, O Daughter of Zion. See, your King is coming, seated on the colt of a donkey.”" },
  { ref: "John 14:1", text: "“Do not let your hearts be troubled. You believe in God; believe in Me as well." },
  { ref: "John 14:27", text: "Peace I leave with you; My peace I give to you. I do not give to you as the world gives. Do not let your hearts be troubled; do not be afraid." },
  { ref: "Acts 18:9", text: "One night the Lord spoke to Paul in a vision: “Do not be afraid; keep on speaking; do not be silent." },
  { ref: "Acts 20:10", text: "But Paul went down, threw himself on the young man, and embraced him. “Do not be alarmed!” he said. “He is still alive!”" },
  { ref: "Acts 27:24", text: "and said, ‘Do not be afraid, Paul; you must stand before Caesar. And look, God has granted you the lives of all who sail with you.’" },
  { ref: "Romans 8:15", text: "For you did not receive a spirit of slavery that returns you to fear, but you received the Spirit of sonship, by whom we cry, “Abba! Father!”" },
  { ref: "Philippians 4:6", text: "Be anxious for nothing, but in everything, by prayer and petition, with thanksgiving, present your requests to God." },
  { ref: "2 Timothy 1:7", text: "For God has not given us a spirit of fear, but of power, love, and self-control." },
  { ref: "Hebrews 13:6", text: "So we say with confidence: “The Lord is my helper; I will not be afraid. What can man do to me?”" },
  { ref: "1 Peter 3:14", text: "But even if you should suffer for what is right, you are blessed. “Do not fear what they fear; do not be shaken.”" },
  { ref: "1 Peter 5:7", text: "Cast all your anxiety on Him, because He cares for you." },
  { ref: "1 John 4:18", text: "There is no fear in love, but perfect love drives out fear, because fear involves punishment. The one who fears has not been perfected in love." },
  { ref: "Revelation 1:17", text: "When I saw Him, I fell at His feet like a dead man. But He placed His right hand on me and said, “Do not be afraid. I am the First and the Last," },
  { ref: "Revelation 2:10", text: "Do not fear what you are about to suffer. Look, the devil is about to throw some of you into prison to test you, and you will suffer tribulation for ten days. Be faithful even unto death, and I will give you the crown of life." },
];
